name: task.sh build
on:
  push:
    branches: ["main"]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .github/**
      - "!.github/workflows/task-build.yml"
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .github/**
      - "!.github/workflows/task-build.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  task-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: ./task.sh setup
      - run: ./task.sh build
      - uses: actions/upload-artifact@v2
        with:
          name: x86_64-unknown-linux-gnu
          path: dist
